### PR TITLE
Feature/uri variables

### PR DESCRIPTION
**Pull request by JeremyLemee**

### CODE REVIEW

**Review by andreiciortea — CHANGES_REQUESTED** [review]
Great, thanks for this work @JeremyLemee! Mostly comments on code styling, which should be addressed before merging. I've added comments wherever I noticed something to make it easy to update. Whenever in doubt about code styling, for this library we follow: https://google.github.io/styleguide/javaguide.html

**Comment by danaivach** [comment]
Jérémy, first of all, thanks a lot for contributing! These are a few comments that address the comformance with the WoT TD Recommendation:
- [URI variables](https://www.w3.org/TR/wot-thing-description/#interactionaffordance) should be of type Map of DataSchema. This is useful, so that you can use keys to refer to URI variables in forms: e.g. 
-- as path parameter in the last form of [ex35](https://www.w3.org/TR/wot-thing-description/#example-35-temperature-event-with-subscription-and-cancellation)
-- as query parameters in the form of [ex21](https://www.w3.org/TR/wot-thing-description/#example-21). 
The mapping could be handled by `TDHttpRequest` in another PR. 
(As an example, the properties of ObjectSchema have been implemented as Map of DataSchema) 
- Ideally, [URI variables](https://www.w3.org/TR/wot-thing-description/#interactionaffordance) should be defined as optional (e.g. like the name and title of InteractionAffordance). 
- ["The individual variables Dataschema cannot be ObjectSchema or ArraySchema"](https://www.w3.org/2019/wot/td#hasUriTemplateSchema). Throwing an `IllegalArgumentException` when someone passes an ObjectSchema or ArraySchema to `addUriVariables`, can be addressed in another PR. But ideally, in this PR, you could remove `testWriteURIVariableObjectSchema` or replace it with one that doesn`t use ObjectSchema/ArraySchema as a URI template schema:
https://github.com/Interactions-HSG/wot-td-java/blob/e1d27daaf555f6a868c9e405b84988b56233e4e1/src/test/java/ch/unisg/ics/interactions/wot/td/io/TDGraphWriterTest.java#L442-L443

**Review by danaivach — CHANGES_REQUESTED** [review]
Jérémy, first of all, thanks a lot for contributing! These are a few comments that address the comformance with the WoT TD Recommendation:
- [URI variables](https://www.w3.org/TR/wot-thing-description/#interactionaffordance) should be of type Map of DataSchema. This is useful, so that you can use keys to refer to URI variables in forms: e.g. 
-- as path parameter in the last form of [ex35](https://www.w3.org/TR/wot-thing-description/#example-35-temperature-event-with-subscription-and-cancellation)
-- as query parameters in the form of [ex21](https://www.w3.org/TR/wot-thing-description/#example-21). 
The mapping could be handled by `TDHttpRequest` in another PR. 
(As an example, the properties of ObjectSchema have been implemented as Map of DataSchema) 
- Ideally, [URI variables](https://www.w3.org/TR/wot-thing-description/#interactionaffordance) should be defined as optional (e.g. like the name and title of InteractionAffordance). 
- ["The individual variables Dataschema cannot be ObjectSchema or ArraySchema"](https://www.w3.org/2019/wot/td#hasUriTemplateSchema). Throwing an `IllegalArgumentException` when someone passes an ObjectSchema or ArraySchema to `addUriVariables`, can be addressed in another PR. But ideally, in this PR, you could remove `testWriteURIVariableObjectSchema` or replace it with one that doesn`t use ObjectSchema/ArraySchema as a URI template schema:
https://github.com/Interactions-HSG/wot-td-java/blob/e1d27daaf555f6a868c9e405b84988b56233e4e1/src/test/java/ch/unisg/ics/interactions/wot/td/io/TDGraphWriterTest.java#L442-L443

**Comment by danaivach** [comment]
Closing - replaced by feature/uri_variables2

**Pull request closed without merging**
